In [2]:
import pandas as pd

In [3]:
times_3k = pd.read_csv(r"C:\Users\Jason\Downloads\DataScience\3k_Times.csv")
times_5k = pd.read_csv(r"C:\Users\Jason\Downloads\DataScience\5k_Times.csv")
times_10k = pd.read_csv(r"C:\Users\Jason\Downloads\DataScience\10k_Times.csv")
times_hm = pd.read_csv(r"C:\Users\Jason\Downloads\DataScience\hm_Times.csv")

In [4]:
comp = times_3k.merge(times_5k, on='Name', how='left').merge(times_10k, on='Name', how='left').merge(times_hm, on='Name', how='left')
comp.dropna(inplace=True)
comp['3k_Pace'] = (pd.to_timedelta('00:' + comp['3k_Time']).dt.total_seconds().astype(int) / 1.86).round(2)
comp['5k_Pace'] = (pd.to_timedelta('00:' + comp['5k_Time']).dt.total_seconds().astype(int) / 3.1).round(2)
comp['10k_Pace'] = (pd.to_timedelta('00:' + comp['10k_Time']).dt.total_seconds().astype(int) / 6.2).round(2)
comp['hm_Pace'] = (pd.to_timedelta(comp['hm_Time']).dt.total_seconds().astype(int) / 13.1).round(2)
comp['5k_perc'] = (comp['3k_Pace'] / comp['5k_Pace']).round(4)
comp['10k_perc'] = (comp['3k_Pace'] / comp['10k_Pace']).round(4)
comp['hm_perc'] = (comp['3k_Pace'] / comp['hm_Pace']).round(4)
comp

,Name,3k_Time,5k_Time,10k_Time,hm_Time,3k_Pace,5k_Pace,10k_Pace,hm_Pace,5k_perc,10k_perc,hm_perc
4,Yomif KEJELCHA,07:23.6,12:39.0,26:31.0,0:57:30,238.17,244.84,256.61,263.36,0.9728,0.9281,0.9044
9,Selemon BAREGA,07:25.8,12:51.4,26:34.9,0:57:50,239.25,248.71,257.10,264.89,0.9620,0.9306,0.9032
10,Thierry NDIKUMWENAYO,07:25.9,12:48.1,26:49.5,0:59:42,239.25,247.74,259.52,273.44,0.9657,0.9219,0.8750
11,Dominic Lokinyomo LOBALU,07:27.7,12:50.9,27:36.3,0:59:12,240.32,248.39,267.10,271.15,0.9675,0.8997,0.8863
19,Jacob KIPLIMO,07:29.6,12:41.0,26:33.9,0:56:42,241.40,245.48,256.94,259.69,0.9834,0.9395,0.9296
...,...,...,...,...,...,...,...,...,...,...,...,...
615,Zakariya MAHAMED,07:54.1,13:24.8,27:46.6,1:01:43,254.84,259.35,268.71,282.67,0.9826,0.9484,0.9015
631,Francesco GUERRA,07:54.4,13:35.9,28:22.1,1:03:19,254.84,262.90,274.52,290.00,0.9693,0.9283,0.8788
639,Torazo KAI,07:54.5,13:36.7,27:56.6,1:02:07,254.84,263.23,270.32,284.50,0.9681,0.9427,0.8957
658,Nickolas SCUDDER,07:54.8,13:33.7,28:28.8,1:04:18,254.84,262.26,275.48,294.50,0.9717,0.9251,0.8653
662,Cosmas Mwangi BOI,07:54.8,13:17.8,27:15.6,0:59:29,254.84,257.10,263.71,272.44,0.9912,0.9664,0.9354

In [11]:
print(250/(comp['5k_perc'].mean()))

257.4204235125576